# Generated by Django 5.1.6 on 2025-07-12 14:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='NovaPoshtaCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField()),
                ('name_ru', models.CharField()),
                ('ref', models.CharField()),
                ('area', models.CharField()),
                ('position', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('ref', models.CharField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='warehouse_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.deliverytype')),
            ],
        ),
        migrations.CreateModel(
            name='NovaPoshtaWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField()),
                ('name_ru', models.CharField()),
                ('ref', models.CharField()),
                ('max_weight_allowed', models.PositiveIntegerField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.novaposhtacity')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.warehousetype')),
            ],
        ),
    ]
