# Generated by Django 5.1.6 on 2025-07-27 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_operator_warehousetype_operator'),
        ('products', '0004_product_quantity_in_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('easypay', 'EasyPay'), ('plata_by_mono', 'plata by mono')], null=True)),
                ('expires_at', models.DateTimeField()),
                ('invoice_id', models.CharField()),
                ('forward_url', models.CharField()),
                ('status', models.CharField(blank=True, choices=[('created', 'Created'), ('processing', 'Processing'), ('hold', 'Hold'), ('success', 'Success'), ('failure', 'Failure'), ('reversed', 'Reversed'), ('expired', 'Expired')], null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('pan', 'PAN'), ('apple', 'Apple Pay'), ('google', 'Google Pay'), ('monobank', 'Monobank'), ('wallet', 'Wallet'), ('direct', 'Direct')], null=True)),
                ('payment_system', models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'MasterCard')], null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='operator',
            name='min_delivery_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('payment_confirmed', 'Payment Confirmed'), ('payment_declined', 'Payment Declined'), ('preparing', 'Preparing'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('received', 'Received'), ('returned', 'Returned'), ('declined', 'Declined')], default='awaiting_payment')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_user_name', models.CharField(max_length=50)),
                ('delivery_user_surname', models.CharField(max_length=50)),
                ('delivery_user_phone', models.CharField(max_length=30)),
                ('delivery_user_email', models.EmailField(max_length=254)),
                ('delivery_city', models.CharField()),
                ('delivery_warehouse', models.CharField(blank=True, null=True)),
                ('delivery_street', models.CharField(blank=True, null=True)),
                ('delivery_house', models.CharField(blank=True, null=True)),
                ('delivery_apartment', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_warehouse_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.warehousetype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
