# Generated by Django 5.1.6 on 2025-08-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_operator_min_delivery_price_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='order',
            name='secret_key',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('payment_declined', 'Payment Declined'), ('preparing', 'Preparing'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('received', 'Received'), ('returned', 'Returned'), ('declined', 'Declined')], default='awaiting_payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='error_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
