# Generated by Django 5.1.14 on 2026-02-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_operator_min_delivery_price_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='secret_key',
        ),
    ]
