# Generated by Django 5.1.14 on 2026-03-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_apartment',
            field=models.CharField(blank=True, null=True),
        ),
    ]
