# Generated by Django 5.1.6 on 2025-12-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_quantity_orderitem_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('payment_declined', 'Payment Declined'), ('preparing', 'Preparing'), ('sent', 'Sent'), ('received', 'Received'), ('returned', 'Returned'), ('declined', 'Declined')], default='awaiting_payment'),
        ),
    ]
