# Generated by Django 5.1.6 on 2026-01-23 11:47

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('show_in_filters', models.BooleanField(default=False, help_text='Показувати у фільтрах')),
                ('show_in_product_details', models.BooleanField(default=False, help_text='Показувати у деталях товару')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', models.OneToOneField(blank=True, help_text='Категорія (pc, laptops і т.ін.), до якої відносяться атрибути', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.category')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productattribute')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(upload_to='products_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])])),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_in_orders', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('attributes', models.ManyToManyField(limit_choices_to={'level': 3}, related_name='products', to='products.productattribute')),
                ('main_attribute', models.ForeignKey(limit_choices_to={'level': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productattribute')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('level__lte', 2)), name='max_level_2'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('level', 0)), models.Q(('category__isnull', True), ('level__gt', 0)), _connector='OR'), name='category_only_on_level_0'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('show_in_filters', False), ('level', 2), _connector='OR'), models.Q(('show_in_product_details', False), ('level', 2), _connector='OR')), name='show_in_filters_and_product_details_only_on_level_2'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level', 3), ('slug__isnull', False)), models.Q(('level__lt', 3), ('slug__isnull', True)), _connector='OR'), name='slug_only_on_level_3'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='unique_attribute_slug_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.CheckConstraint(condition=models.Q(('level__lte', 3)), name='max_level_3'),
        ),
    ]
