# Generated by Django 5.1.6 on 2026-01-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(max_length=255, unique=True)),
                ('public_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_links', to='products.product')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.productvariantgroup')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('group', 'product')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='variant_groups',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductVariant', to='products.productvariantgroup'),
        ),
    ]
