# Generated by Django 5.1.6 on 2025-07-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_weight_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_in_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
