# Generated by Django 5.1.14 on 2026-02-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='show_in_short_info',
            field=models.BooleanField(default=False, help_text='Відображати в коротких характеристиках товару'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.CheckConstraint(condition=models.Q(('show_in_short_info', False), ('level__in', [1, 2]), _connector='OR'), name='show_in_short_info_only_on_level_1_or_2'),
        ),
    ]
